### ISSUE TITLE
Package for PHP 7.x?

### ISSUE THREAD

**Issue by jamespatterson** [iuscommunity-pkg/php56u-pecl-ssh2#1]
I was trying to upgrade from PHP 5.6 to 7.0 on CentOS 6 and 7, but neither IUS repo has a php70u-pecl-ssh2 package available. Is one planned or is there a way to contribute one if not? I'd rather not clutter up production servers with compilers and libraries just to install a PECL extension.

**Comment by b-harper** [comment]
Hey @jamespatterson,

Please see iuscommunity/wishlist#88 for more information regarding the status of pecl ssh2 module.

**Comment by jamespatterson** [comment]
When I saw other repos like Remi have a package for CentOS 7, I thought maybe it was an oversight. Sadly this delays my PHP7 deployment even longer. Thanks for pointing me to the wishlist, too. I didn't find that previously.

**Comment by b-harper** [comment]
You are welcome.  The transition from PHP5 to PHP7 has been tough for some modules.  We have a [few more requests][0] for modules that don't have a stable PHP7 release.

I would recommend watching iuscommunity/wishlist#88 as we will work out of that issue if/when the ssh2 module gets a stable release for PHP7.

[0]: https://github.com/iuscommunity/wishlist/labels/pending%20upstream
